ktor:
  development: true
  deployment:
    port: 8080
    watch:
      - classes
      - resources
  application:
    modules:
      - com.example.ApplicationKt.module
storage:
  database: "ktor_tutorial_db"
  jdbcURL: "jdbc:postgresql://localhost:5432/ktor_tutorial_db"
  user: "postgres"
  password: "password"
